# Generated by Django 4.0.6 on 2022-07-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='cumpleanos',
            field=models.DateField(default='2006-03-31'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
